---
title: "Chapter 3"
author: "Dominik Klepl"
date: "4 3 2018"
output: html_document
---

```{r setup, include=FALSE}
library(rethinking)
library(ggplot2)
```

#Practice

##EASY
```{r}
#data to use
p_grid = seq( from=0 , to=1 , length.out=1000 )
prior = rep( 1 , 1000 )
likelihood = dbinom( 6 , size=9 , prob=p_grid )
posterior = likelihood * prior
posterior = posterior / sum(posterior)
set.seed(100) #to make the samples stable and comparable to results in the book
samples = sample( p_grid , prob=posterior , size=10^4 , replace=TRUE )
```

###3E1
How much post. prob. lies below 0.2?
```{r}
sum( samples < 0.2 ) / 10^4
sum(posterior[p_grid<0.2])
```
###3E2
How much post. prob. lies above 0.8?
```{r}
sum( samples > 0.8 ) / 10^4
sum(posterior[p_grid>0.8])
```

###3E3
How much post. prob. lies between 0.2 and 0.8?
```{r}
sum( samples > 0.2 & samples < 0.8 ) / 10^4

#and answers from 1, 2 and 3 adds up to 1
```

###3E4 and 3E5

```{r}
quantile( samples , 0.2 )

quantile( samples ,  c(0.8,1))
```

###3E6
```{r}
HPDI(samples, prob=.66)
```

###3E7
```{r}
PI(samples,prob=.66)
```


#MEDIUM

###3M1
```{r}
p_grid = seq( from=0 , to=1 , length.out=1000 )
prior = rep( 1 , 1000 )
likelihood = dbinom( 8 , size=15 , prob=p_grid )
posterior = likelihood * prior
posterior = posterior / sum(posterior)
set.seed(100) #to make the samples stable
```

###3M2
```{r}
samples = sample( p_grid , prob=posterior , size=10^4 , replace=TRUE )
HPDI(samples,prob=.90)
```

###3M3
```{r}
post_pred_distr = sample( p_grid , prob=posterior , size=10^4 , replace=TRUE )

samples = rbinom( 10^4 , size=15 , prob=post_pred_distr )
mean(samples==8)
```

###3M4
```{r}
samples = rbinom( 10^4 , size=9 , prob= post_pred_distr)
mean(samples==6)
```

###3M5
```{r}
p_grid = seq( from=0 , to=1 , length.out=1000 )
prior = ifelse(test = p_grid < .5, yes = 0, no = 1)
likelihood = dbinom( 8 , size=15 , prob=p_grid )
posterior = likelihood * prior
posterior = posterior / sum(posterior)
set.seed(100) #to make the samples stable and comparable to results in the book

#repeat 3M2
samples = sample( p_grid , prob=posterior , size=10^4 , replace=TRUE )
HPDI(samples,prob=.90)

#repeat 3M3
post_pred_distr = sample( p_grid , prob=posterior , size=10^4 , replace=TRUE )

samples = rbinom( 10^4 , size=15 , prob=post_pred_distr )
mean(samples==8)

samples = rbinom( 10^4 , size=9 , prob= post_pred_distr)
mean(samples==6)
```

## HARD
### Intro
```{r}
## R code 3.29
library(rethinking)
data(homeworkch3)

## R code 3.30
data = as.data.frame(cbind(birth1,birth2))
```

### 3H1
```{r}
all_births = nrow(data)*2
boys = sum(data)
girls = all_births-boys

#get posterior distribution with grid approximation
p_grid = seq( from=0 , to=1 , length.out=1000 )
prior = rep( 1 , 1000 )
likelihood = dbinom( boys , size=all_births , prob=p_grid )
posterior = likelihood * prior
posterior = posterior / sum(posterior)
set.seed(100) #to make the samples stable

plot(posterior ~ p_grid, type = "l")

p_grid[which.max(posterior)]
```

###3H2
```{r}
samples = sample(p_grid, prob=posterior,size=10^4,replace=T)

intervals = c(.5,.89,.97)

for (i in intervals) {
  print(HPDI(samples,i))
}
```

### 3H3
```{r}
predictions = rbinom( 10^4 , size=200 , prob=samples )

dens(predictions)

dens(predictions)
  abline(v = boys, col = "red") #model seems to be fitting pretty nicely
```

### 3H4
```{r}
#get samples again
samples = sample(p_grid, prob=posterior,size=10^4,replace=T)

#count number of boys born as the first-child
first_boy = sum(data[,1])
births=100

simul = rbinom( 10^4 , size=100 , prob=samples )

dens(simul,adj=1)
  abline(v=first_boy, col="red") #that's not very good, although still kinda close
```

### 3H5
```{r}
boys_after_girls=sum(data$birth2[data$birth1==0])
first_girl = as.numeric(sum(data$birth1==0))

sims = rbinom(10^4, size=first_girl,prob=samples)

dens(sims) 
  abline(v=boys_after_girls, col="red") #births are not independent therefore model performs badly
```
